// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM4tvdNqoL4yupzeBd0EyQ4uArBQSPrYw',
    appId: '1:1026764741396:web:6e1757a027f13e7513c001',
    messagingSenderId: '1026764741396',
    projectId: 'it-project-kitti-ccc7c',
    authDomain: 'it-project-kitti-ccc7c.firebaseapp.com',
    storageBucket: 'it-project-kitti-ccc7c.appspot.com',
    measurementId: 'G-HJ7MYGNWG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzxJAbFm2Noi9D9rt-SuOOY1N89y19jhQ',
    appId: '1:1026764741396:android:197348845f93d60b13c001',
    messagingSenderId: '1026764741396',
    projectId: 'it-project-kitti-ccc7c',
    storageBucket: 'it-project-kitti-ccc7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHM5Ro3sGnjWmUcLivE9b_0L5hzyOkDWc',
    appId: '1:1026764741396:ios:5e2589620ce67e2213c001',
    messagingSenderId: '1026764741396',
    projectId: 'it-project-kitti-ccc7c',
    storageBucket: 'it-project-kitti-ccc7c.appspot.com',
    iosClientId:
        '1026764741396-3eub4hhgt6eqjuakjit8bp7n5h5ho12e.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsStudyKitti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHM5Ro3sGnjWmUcLivE9b_0L5hzyOkDWc',
    appId: '1:1026764741396:ios:5e2589620ce67e2213c001',
    messagingSenderId: '1026764741396',
    projectId: 'it-project-kitti-ccc7c',
    storageBucket: 'it-project-kitti-ccc7c.appspot.com',
    iosClientId:
        '1026764741396-3eub4hhgt6eqjuakjit8bp7n5h5ho12e.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsStudyKitti',
  );
}
